Add has_access method to handle backward compatibility
astronomer/airflow-dbcleanup-plugin pull request #21
Opened 2023-10-04 18:16 UTC by utkarsharma2

Related to - https://github.com/apache/airflow/pull/33213/files#r1343788762

Slack thread - https://astronomer.slack.com/archives/C01UJJEN0P3/p1696316567678809

2023-10-05 20:33 UTC, utkarsharma2 commented
Closing this PR as it's no longer needed because of the following changes - https://github.com/apache/airflow/pull/34786#pullrequestreview-1660614666

2023-10-11 14:29 UTC, ephraimbuddy requested changes

2023-10-11 14:29 UTC, ephraimbuddy commented on dbcleanup_plugin.py
> +        ("can_dismiss", 'UpdateAvailable'),
```suggestion
        ("can_access_dbcleanup", "AstronomerDbcleanup"),
```

2023-10-11 14:31 UTC, ephraimbuddy approved these changes

2023-10-11 19:28 UTC, merged